In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_json('cleandf.json')

In [5]:
len(df)

6975

In [6]:
df.columns

Index(['cur', 'description', 'favorites', 'image_urls', 'images', 'overview',
       'price', 'script', 'title', 'rating_count', 'materials', 'gold',
       'silver', 'diamond', 'brass', 'vintage', 'year', 'handmade', 'desc',
       'adesc'],
      dtype='object')

In [7]:
d2v_cossim = np.load('d2v-cossim.npy')

In [11]:
d2vcossim = d2v_cossim.astype(np.float64)

In [12]:
eps = 1e-15

In [14]:
np.max(d2vcossim[d2vcossim<1.0-eps])

0.9999999403953552

In [16]:
np.argpartition(d2vcossim[:,0],-4)[:4]

array([3778, 6974,    2, 6973])

In [18]:
d2vcossim[np.argpartition(d2vcossim[:,0],-4)[-4:],0]

array([0.60665441, 0.60701919, 0.62340331, 1.00000012])

In [19]:
d2vcossim[np.logical_and(d2vcossim<0.99, d2vcossim>0.98)]

array([0.98443043, 0.98813474, 0.98907369, ..., 0.98081815, 0.98887551,
       0.98458266])

In [21]:
np.where(np.logical_and(d2vcossim<0.99, d2vcossim>0.98))

(array([   1,    1,    1, ..., 6920, 6951, 6971]),
 array([ 862, 1748, 2324, ..., 6172,  133, 5729]))

In [22]:
d2vcossim[1,862]

0.9844304323196411

In [38]:
df.iloc[862].adesc

'package sent via international registered air mail takes days arrive upgrade shipping ems express mail takes days arrive personalized name necklace gold name necklace personalized name necklace personalized jewelryname necklace gift measurements name plate changes according name order feel free contact questions come see gold name necklaces stephenie lengths available necklaces packaged shipped beautiful gift box best wishes takes days make necklaces dont forget write name wish note box checkout page shipping info name necklace info general info order necklace rhodium rose gold plated choose name word letters name pendant chain yellow gold plated name plate thick'

In [39]:
df.iloc[1748].adesc

'package sent via international registered air mail takes days arrive upgrade shipping ems express mail takes days arrive feel free contact questions measurements name plate changes according name order name necklace hebrew come see gold name necklaces stephenie name necklace gold plated name necklace gold personalized name necklaces gold name necklace personalized jewelry gifts lengths available necklaces packaged shipped beautiful gift box best wishes takes days make necklaces dont forget write name wish note box checkout page order necklace sterling silver rose gold plated shipping info name necklace info general info choose name word letters name pendant chain made yellow gold plated name plate thick'

In [94]:
np.where(np.logical_and(d2vcossim<0.82, d2vcossim>0.81))

(array([   1,    1,   23, ..., 6956, 6956, 6961]),
 array([ 683, 2672, 2671, ..., 1454, 3810,  885]))

In [101]:
df.iloc[6961].description

'this necklace is very delicate  but strong  handcrochet  with genuine bicone 4 mm swarovski beads and a sterling silver clasp'

In [100]:
df.iloc[885].description

'this beautiful necklace has turquoise beads seed beads pewter silver bead caps pewter silver pendant with rhinestone accent and sterling silver plated feather drops  18 long sterling silver plated toggle clasp turquoise necklace'

In [102]:
d2vcossim[885,6961]

0.8166753649711609

In [78]:
df.iloc[6899].desc

'etsy guide purchase credit card paypal 100 cotton crochet necklace ready ship worldwide flower 4 16 3 12 feel free ask questions ready ship 2-3 business days list growing stay tuned thank accepting paypal 190 cm76'

In [80]:
df.iloc[1077].desc

'rose 18 100 cotton crochet necklace ready ship worldwide feel free ask questions ready ship 2-3 business days list growing stay tuned flower 35 14 51 204 ties 32 128 side thank'

## Images

In [103]:
img_cossim = np.load('img_cossim.npy')

In [104]:
imgcossim = img_cossim.astype(np.float64)

In [105]:
np.where(np.logical_and(imgcossim<0.82, imgcossim>0.81))

(array([   2,   22,   26, ..., 6957, 6957, 6962]),
 array([2548, 5845, 1451, ..., 4093, 5584, 4231]))

In [111]:
df.iloc[22].images

[{'url': 'https://i.etsystatic.com/6050455/r/il/27829c/1248489421/il_fullxfull.1248489421_58rv.jpg',
  'path': 'full/34d1ea0e5de555eb207d1fffb524e91ec6ee5ffd.jpg',
  'checksum': 'c21b48d216f51685904fc54bf8f328d3'}]

In [112]:
df.iloc[5845].images

[{'url': 'https://i.etsystatic.com/6995048/r/il/595176/1160553848/il_fullxfull.1160553848_peg6.jpg',
  'path': 'full/e1a6a1623dee6b76229f87d286bcbb3c032fff3e.jpg',
  'checksum': 'd07746a7e252d48ab7da006864fa31b6'}]

In [113]:
imgcossim[22,5845]

0.8129962626575791